#+title: Trip

Je sauve ici l'ensemble des trajets possibles, biscornus ou non.

** Le début
Commençons par la lettre "A", première et primaire:
Rue de l'Aqueduc, Rue Louis Blanc, Boulevard de la Chapelle, Rue du Faubourg Saint-Denis, Rue du Château d'Eau, Rue du Faubourg Saint-Martin, Rue Gustave Goublier. Petite rue, dont le nom m'avait toujours échappé, alors que je l'avais prise de nombreuses fois quand je vivais dans ce quartier.

Prendre le bus 38 (trente-Huit, des barres), jusqu'à l'arrêt Alesia Maine, pour rejoindre la rue Hallé (ou pas vu que nous avons déjà le trente-huit).

Autre possibilité: rejoindre la place Jules Henaffe.

La suivre jusqu'à l'avenue René Coty. Faire un détour par le 28 avenue rené Coty, mon premier appart à paris; et retrouver la rue de la Tombe Issoire.

Suivre ensuite:
Rue de la Tombe Issoire, Boulevard Jourdan: prenre le tram jusque arret Damesme (on passe donc par le Boulevard Kellermann), revenir sur Rue du Professeur Louis Renault, Rue Max Jacob. C'est ici que j'ai joué au tennis avec Sophie et son père.

-> Se rendre à Pont Neuf via Maison Blanche et la 7.

Pont Neuf, Quai des Orfèvres, Boulevard du Palais, Quai de l'Horloge


Que faire ensuite pour le R?

Possibilité: prendre le 76 à chatelet, Avenue Ledru rollin, rue du fbg saint antoine puis rue traversière

** Autre Possibilité pour P
Pont Neuf, Quai des Orfèvres, Pont Saint-Michel, Quai des Grands Augustins, Promenade René Capitant, Place Saint-Michel

-> mène au T:
Prendre le 21/27 (on garde le Sept) ->
Rue Louis Thuillier, Rue d'Ulm

Ce qui nous mène au V, autre grande lettre.

** V, la lettre V, et sa soeur W
Rien de bien reluisant ici:
[Villa Nouvelle, Avenue de Wagram]
[Rue des Frères d'Astier de la Vigerie, Rue Simone Weil] -> 13eme again
[Boulevard Vincent Auriol, Rue Louise Weiss]
[Avenue de la Porte de Vincennes, Rue Albert Willemetz]
[Rue Mies Van Der Rohe, Rue Frank Lloyd Wright]
[Avenue de Versailles, Rue Wilhem]
[Avenue de Villiers, Avenue de Wagram]


** Du X au Y
Comme il n'y a qu'une rue avec un X, rue Xavier Privas (à côté de saint michel).
regardons les voies en Y:
Promenade Yehudi Menuhin
Place du Docteur Yersin
Rue Yvonne Le Tac
Rue Saint-Yves
Avenue de New York


** La fin en Z
Rue Boy-Zelenski, vers Colonel Fabien
Rue Felix Ziem, non loin du cimetière Montmartre
